### ISSUE TITLE
Bundling browser JS from Rust

### ISSUE THREAD

**Issue by tgrushka** [alshdavid/mach#19]
Hi @alshdavid, I came across your article here: https://www.davidalsh.com/posts/writing-a-bundler-part-1/ and was hoping to read parts 2 and 3, but noticed that the repo at [link to source](https://github.com/alshdavid/davidalsh-com/tree/main/posts/2023-12-14-how-fast-can-you-bundle-part-1/sources/single-threaded-transformer) has been removed.

I guess this is a feature proposal or for your thoughts on it.

I am building a specific web testing suite in Rust using [thirtyfour](https://crates.io/crates/thirtyfour) or [chromiumoxide](https://crates.io/crates/chromiumoxide). Many of my testing tools run as JavaScript in the browser context, and I am building specific tooling around them that must run in-browser. This testing suite is deployed to serverless workers in the cloud using Docker. (My huge test suite is currently in TypeScript compiled with Bun but this presents longevity and maintenance problems that seem to keep popping up every time a dependency or Bun is updated, not to mention having to bundle node_modules for the entire workspace, the lack of tree-shaking in Bun -- can't even go back to Node.js because I've used Bun's specific importing "magic" -- and things generally breaking every other time I deploy -- hence I'm rebuilding everything in Rust.) Therefore, I am writing all of my in-browser test tooling code in TypeScript, and wish to type-check, transpile, and bundle it at **compile time** in `build.rs` in my Rust project. If there's a TypeScript error in my code, the build should fail. I then intend to use [rust-embed](https://crates.io/crates/rust-embed) to load the transpiled JavaScript bundle files statically into my single binary that will run in a Docker container.

Am I crazy, or the first/only one, who wants to bundle JavaScript **from Rust code**, instead of a separate pre-compiled CLI tool? I've looked at all projects (swc, deno, turbopack) and none of them have friendly APIs to just bundle a package **from Rust code**. Why is this? You'd think a Rust API would be a 1st-class citizen among Rust developers!

Fortunately, I came across your crate here, and was able to fork it and add two lines of code to `mach/src/lib.rs`:
```
pub mod cmd;
pub mod platform;
```

This made these modules public and I was able to test it like this:
```rs
use std::path::Path;

use mach::cmd::build::{main as build, BuildCommand};

fn main() {
    let entry_point = Path::new("./index.ts").to_path_buf();
    let out_folder = Path::new("./build").to_path_buf();

    let command = BuildCommand {
        entry: Some(vec![entry_point]),
        out_folder,
        clean: true,
        no_optimize: false,
        bundle_splitting: false,
        threads: None,
        node_workers: None,
        debug: true,
    };
    let _ = build(command);
}
```

What are your thoughts on this? Should the resulting bundles work in web? (I'm new to Rust and swc is pretty complex.) Are you intending to develop/maintain this crate further and, if so, would you be willing to expose your API a bit more so that custom bundlers can be built on it in Rust?

I would consider putting these requests into swc, deno, turbo but I get the impression those projects have other priorities, and the swc maintainer has moved on to Vercel and claims their bundler isn't even being maintained.

Thanks!

**Comment by alshdavid** [comment]
Hi @tgrushka, thanks for raising an issue, appreciate you looking at the project and engaging. It's motivational to know that the project might prove helpful for others.

> I came across your article here: https://www.davidalsh.com/posts/writing-a-bundler-part-1/ and was hoping to read parts 2 and 3

I'm glad that you found the article interesting, will certainly look at continuing the series after getting Mach into a stable state. I feel it would be helpful to future contributors as it would serve as good foundational documentation.

It's funny, I went back to writing the next installment in the series but I felt markdown was too restrictive to write things in a way that was ergonomic to read, so I wanted to upgrade my website first. 

My site is using a custom pseudo-bundler that I don't like very much so in the process of updating it I decided to build the bundler I wanted to see, which would also offer a good place to get examples for the article for. 

A few months later I'm deep into building a serious bundler project haha. Feels very much like this scene from [Malcolm in the Middle](https://www.youtube.com/watch?v=AbSehcT19u0)

> Am I crazy, or the first/only one, who wants to bundle JavaScript from Rust code, instead of a separate pre-compiled CLI tool?

Sounds rational to me, but I'm not sure I am any less crazy given I am writing a bundler 😆

I have actually just started implementing programmatic invocation for Mach to help facilitate the integration suite. I intend to support 3 programmatic consumer types:

- JavaScript/TypeScript 
  - Via npm, create`new Mach()`, partial support now
- Rust 
  - Not sure what to call the crate yet, naming is hard, maybe `mach_core`, `libmach` or something
- Dynamic C library 
  - So bindings can be written for Go, Dart, etc

I want to keep Mach open to consumers from other languages, that goes for plugins and for programmatic usage. 

My first use case is the integration test suite for Mach which is written in TypeScript (I want to use Puppeteer) so I have just implemented basic support for programmatic invocation in JS.

> This made these modules public and I was able to test it like this:

Architecturally, I tried to keep the Rust source easy to make usable programmatically in the future. Pretty awesome to see that you were able to get something working with minimal changes.

You will probably get a bunch of unwanted terminal output at the moment because I haven't implemented "Reportes" yet. 

> I am writing all of my in-browser test tooling code in TypeScript, and wish to type-check, transpile, and bundle it at compile time in build.rs in my Rust project

This is an interesting use-case. I don't think any bundler does type checking natively, they all call out to the TypeScript compiler (`tsc`) for that.

At present, Mach only strips types from sources and you need to do a type checking pass prior to bundling. 

Unfortunately the TypeScript compiler is written in JavaScript so there is no way around needing a JS environment to run `tsc`. 

I was experimenting with creating a crate that wrapped `tsc`, running it internally with [quickjs](https://github.com/theduke/quickjs-rs) - but there's only so much I can do as one person so my focus is finishing the bundler first 😅

In the interim, you can spin up `tsc` from a child process in `build.rs` and fail the build if it doesn't complete successfully, continuing onto bundling if it's successful.

> Are you intending to develop/maintain this crate further, if so, would you be willing to expose your API a bit more so that custom bundlers can be built on it in Rust?

100%. I will be splitting the `mach` crate into two crates, `mach_core` and `mach_cli`. 

`mach_core` will contain the bundler core logic and programmatic API while `mach_cli` is just a consumer that exposes the behaviour via a CLI. I intend to publish `mach_core` to crates.io.

I haven't had a need for this yet, given the project is still in the early stages of development and no one has asked for it but given your question I'll do that shortly.

Keep in mind that I'm actively working on the bundler and while it will eventually be stable, I hope the current frequency of updates and breaking changes isn't overwhelming.

**Comment by alshdavid** [comment]
I've moved the core functionality to a the [mach_bundler_core](https://github.com/alshdavid/mach/tree/main/crates/mach_bundler_core) crate internally, just need to publish it to crates.io

**Comment by alshdavid** [comment]
Published to crates.io as [mach_bundler_core](https://crates.io/crates/mach_bundler_core)

For usage see [mach_bundler_cli](https://github.com/alshdavid/mach/blob/main/crates/mach_bundler_cli/src/main.rs).

For nodejs plugin support you will need to initialize a [nodejs plugin runtime environment](https://github.com/alshdavid/mach/blob/main/crates/mach_bundler_cli/src/main.rs#L27) and pass it into the `Mach.build` method. 

The plugin runtime is [included in `mach_bundler_core`](https://github.com/alshdavid/mach/blob/main/crates/mach_bundler_core/src/adapters/nodejs_ipc/nodejs_ipc_adapter.rs) but the Nodejs glue code is not.

In future I will embed the glue code into the library but for now you'll need to supply the glue code manually alongside the binary.

Glue code sources are here: https://github.com/alshdavid/mach/tree/main/npm/mach-os-arch
You can get the built glue code from the [github release](https://github.com/alshdavid/mach/releases/tag/0.0.68) or [npm](https://www.npmjs.com/package/@alshdavid/mach-linux-amd64)

**Comment by alshdavid** [comment]
Keep in mind the bundling output is not yet valid for all cases. I'm about to start rewriting the graph implementation, graph builder and packager to account for that. 

Again, still early days and I am making a lot of changes to the bundler

**Comment by tgrushka** [comment]
Hmmm, very cool! Seems OK for this small example.

Is the bundle output expected to be es5/es2020/what flavor js? Is it configurable in tsconfig.json or is that ignored?

Would appreciate ability to specify static output filename, i.e. `bundle.js`, instead of content-hash filename (realize many people want the hash so fine with me if that remains the default unless bundle filename is specified). With the content-hash name I have to rename it anyway so it will resolve statically with rust-embed and I won't have to update the name in code. (I love how Rust just resolves a sub-package even in a monorepo -- too bad Dart can't do that.)

Cargo.toml:
```toml
mach_bundler_core = { version = "0.0.0-local", git = "https://github.com/alshdavid/mach" }
```

ts/index.ts:
```ts
function hello() {
    console.log('hello')
}

window.hello = hello
```

main.rs:
```rs
use std::{
    fs::{copy, create_dir_all},
    path::{Path, PathBuf},
};

use mach_bundler_core::{BuildOptions, Mach};

fn unwrap_path(path: &str) -> PathBuf {
    Path::new(path).canonicalize().unwrap()
}

fn main() {
    let entry_point = unwrap_path("./ts");
    let build_path = unwrap_path("./build");

    let options = BuildOptions {
        entries: None,
        out_folder: build_path.clone(),
        project_root: Some(entry_point),
        // would be cool to have bundle_file: None or Some(name) or similar
        clean: true,
        optimize: false,
        bundle_splitting: false,
        threads: None,
        node_workers: None,
        adapter_map: None,
    };

    println!("options = {:#?}", options);

    let result = Mach::new().build(options);

    let result = match result {
        Ok(result) => result,
        Err(error) => panic!("{}", error),
    };

    let bundle_file_name = result.entries.get("index.ts").unwrap();
    let built_bundle = build_path.join(Path::new(bundle_file_name));
    let assets = unwrap_path("./assets");
    let bundle = assets.join(Path::new("bundle.js"));
    println!("built_bundle = {:#?}", built_bundle);
    println!("bundle = {:#?}", bundle);
    let create_dir_res = create_dir_all(assets);
    let copy_res = copy(built_bundle, bundle);
    println!("create_dir_res = {:#?}", create_dir_res);
    println!("copy_res = {:#?}", copy_res);
}
```

(formatted) transformed bundle.js:
```js
(async () => {
    const mach_global = globalThis["PROJECT_HASH"] = globalThis["PROJECT_HASH"] || new EventTarget;
    const mach_init = mach_global.init = mach_global.init || {};
    const mach_modules = mach_global.modules = mach_global.modules || {};
    const mach_manifest = mach_global.manifest = mach_global.manifest || {};
    const mach_bundles = mach_global.bundles = mach_global.bundles || {};
    const mach_bundle_src = "c0c5b2de6a8e919.js";
    const document = globalThis.document;
    const window = globalThis;
    mach_init["index.ts"] = (mach_require, define_export, modules, module_id) => {
        function hello() {
            console.log("hello");
        }
        window.hello = hello;
    };
    const mach_define_property = mach_global.mach_define_property = (target, key, getter, setter, settings = true) => Object.defineProperty(target, key, {
        get: getter,
        set: setter,
        enumerable: settings,
        configurable: settings
    });
    const mach_require = mach_global.mach_require = (module_id, bundle_ids, callback) => {
        if (mach_modules[module_id]) {
            callback && callback(mach_modules[module_id]);
            return mach_modules[module_id];
        }
        mach_modules[module_id] = {};
        const define_export = (...args) => mach_define_property(mach_modules[module_id], ...args);
        const run_init = () => {
            mach_init[module_id](mach_require, define_export, mach_modules, module_id);
            mach_init[module_id] = undefined;
            callback && callback(mach_modules[module_id]);
            return mach_modules[module_id];
        };
        if (bundle_ids && bundle_ids.length) {
            return Promise.all(bundle_ids.map(bundle_id => import_script(mach_manifest[bundle_id]))).then(run_init);
        }
        return run_init();
    };
    mach_require("index.ts");
    mach_bundles[mach_bundle_src] = true;
    mach_global.dispatchEvent(new CustomEvent("bundle_loaded", {
        detail: mach_bundle_src
    }));
})();
```

**Comment by alshdavid** [comment]
> Is the bundle output expected to be es5/es2020/what flavor js?

At the moment I have a basic universal packaging format that is designed to be run as an entry point from any runtime (cjs, module, browser).

On the roadmap is specifying a "target" (like in Parcel) which describes the runtime of the target consumer. This will allow for bundles to target Nodejs cjs, Nodejs esm, Browser esm, Browser script tag.

Later there will be the need to bundle for library consumers (like with esbuild), but I'm a little while away from that still.

> Would appreciate ability to specify static output filename

That's the part I'm working on at the moment. Single bundle vs split bundle outputs require a better graph implementation (right now mine is very basic) 

> Cargo.toml

I accidentally published the wrong version and yanked it. I republished it under 0.0.* (https://crates.io/crates/mach_bundler_core/0.0.68)

> (formatted) transformed bundle.js:

Right now I have a basic runtime that facilitates lazy loading and is shipped along with the code. In a future revision this will be augmented based on the target. Single bundles don't need it so it will be omitted.
